load("//Config:configs.bzl", "app_binary_configs", "library_configs", "watch_binary_configs", "message_binary_configs", "pretty", "info_plist_substitutions")
load("//Config:buck_rule_macros.bzl", "apple_lib", "apple_test_lib", "apple_test_all")

apple_asset_catalog(
  name = "AppAsset",
  dirs = ["Assets.xcassets"],
  app_icon = "AppIcon",
)
apple_resource(
    name = "AppResources",
    files = glob(["**/*.storyboard"]),
)


apple_library(
    name = "AppLibrary",
    configs = library_configs(),
    swift_version = "5",
    srcs = glob(["*.swift"]),
    deps = [
       "//Pods:Alamofire",
        "//Pods:IGListKit",
        #"//Pods:FirebaseCore",
        #"//Pods:FirebaseAuth",
        "//Pods:Swinject",
        "//Pods:SwinjectStoryboard",
        "//Pods:RxSwift",
        "//Pods:RxCocoa",
#         "//Pods:KochavaTrackeriOS",
         #"//Pods:ZDCChat",
         #"//Pods:ZDCChatAPI",
         #"//Pods:Fabric",
         #"//Pods:Crashlytics",
         #"//Pods:Mixpanel",
         "//Pods:SwiftyRSA",
         #"//Pods:SwiftKeychainWrapper",
         #"//Pods:SkyFloatingLabelTextField",
         #"//Pods:CountryPickerSwift",
         "//Pods:Validator",
         "//Pods:SVProgressHUD",
         #"//Pods:Intercom",
         "//Pods:Hero",
         "//Pods:Lottie",
         #"//Pods:Armchair",
         "//Pods:IQKeyboardManagerSwift",
#         "//Pods:ZendeskCoreSDK",
#         "//Pods:ZendeskProviderSDK",
#         "//Pods:ZendeskSDK",
        #"//Pods:FBSDKCoreKit",
        #"//Pods:Protobuf",
        #"//Pods:FirebaseMessaging"
        ":AppAsset",
        ":AppResources"

    ]
)
apple_binary(
    name = "AppBinary",
    configs = app_binary_configs("BuckTest"),
    swift_version = "5.1",
    srcs = [
        "BuckSupportFiles/Dummy.swift",
    ],
    deps = [":AppLibrary"],
    frameworks = [
        '$SDKROOT/System/Library/Frameworks/Foundation.framework',
        '$SDKROOT/System/Library/Frameworks/UIKit.framework',
        '$SDKROOT/System/Library/Frameworks/AssetsLibrary.framework',
        '$SDKROOT/System/Library/Frameworks/CoreTelephony.framework',
    ],
)
ui_tests = [
    ":XCUITests",
]
xcode_workspace_config(
    name = "workspace",
    workspace_name = "BuckTest",
    src_target = ":BuckTest",
    additional_scheme_actions = {
        "Build": {
            "PRE_SCHEME_ACTIONS": ["echo 'Started'"],
            "POST_SCHEME_ACTIONS": ["echo 'Finished'"],
        },
    },
    extra_tests = ui_tests,
    action_config_names = {"profile": "Profile"},
)
apple_bundle(
    name = "BuckTest",
    extension = "app",
    binary = ":AppBinary",
    product_name = "BuckTest",
    info_plist = "Info.plist",
    info_plist_substitutions = info_plist_substitutions("BuckTest"),
)


apple_package(
  name = "BuckTestAppPackage",
  bundle = ":BuckTest",
)

apple_test(
    name = "AppTest",
    test_host_app = ":App",
    srcs = glob(["BuckTestTests/*.swift"]),
    info_plist = "Info.plist",
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)



# This test suite cannot be packaged with other tests due to a dependency on `fbxctest` instead of `xctool`.
apple_test_lib(
    name = "XCUITests",
    destination_specifier = {
        "name": "iPhone 8",
    },
    run_test_separately = True,
    # The `test_host_app` is launched first in the Simulator and needs to be an `apple_bundle` that is distinct from `ui_test_target_app`.
    test_host_app = ":XCUITestsHostApp",
    srcs = glob([
        "BuckTestUITests/*.swift",
    ]),
    is_ui_test = True,
    # The `ui_test_target_app` field is not mentioned in Buck's official documentation, but it appears in its XCUITest fixtures.
    # https://github.com/facebook/buck/blob/master/test/com/facebook/buck/apple/testdata/apple_test_xcuitest/BUCK.fixture#L66
    ui_test_target_app = ":BuckTest",
    labels = ['ui'],
    frameworks = [
        "$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework",
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)


# A very thin host app to enable running :XCUITests
apple_bundle(
    name = "XCUITestsHostApp",
    extension = "app",
    binary = ":XCUITestsHostAppBinary",
    product_name = "XCUITestsHostApp",
    info_plist = "Info.plist",
    info_plist_substitutions = info_plist_substitutions("XCUITestsHostApp"),
)

apple_binary(
    name = "XCUITestsHostAppBinary",
    configs = app_binary_configs("XCUITestsHostAppBinary"),
    swift_version = "5",
    srcs = [
        "BuckSupportFiles/DummyAppDelegate.swift",
    ],
)

### Tests End ###